name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, linux]
    container:
      image: 'ghcr.io/cracked-machine/yocto_xlnx:ubuntu2204'
    steps:
        # only v1 works within a self-hosted containerized actions-runner :(
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: 'true'

      - name: test
        run: ls -la & pwd
      
      - name: build linux 
        run: |
          cd layers/poky
          source oe-init-build-env ../build/custom_zcu104
          bitbake core-image-minimal

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: yocto_xlnx-${{ github.sha }}
          path: ../build/tmp/deploy/images/qemu${{ matrix.arch }}/
          