name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, linux]
    container:
      image: 'ghcr.io/cracked-machine/yocto_xlnx:ubuntu2204'
    steps:
        # only v1 works within a self-hosted containerized actions-runner :(
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: 'true'

      - name: print env
        run: env && ls -la ${GITHUB_WORKSPACE}
    
      - name: build linux 
        run: |
          cd ${GITHUB_WORKSPACE}/layers/poky
          . ./oe-init-build-env ${GITHUB_WORKSPACE}/build/custom_zcu104
          bitbake core-image-minimal

      - name: Store artifacts
        uses: actions/upload-artifact@v1
        with:
          name: yocto_xlnx-${{ github.sha }}
          path: .${GITHUB_WORKSPACE}/build/custom_zcu104/tmp/deploy/images/*
          
          