name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, linux]
    container:
      image: 'ghcr.io/cracked-machine/yocto_xlnx:ubuntu2204'
    steps:
        # only v1 works within a self-hosted containerized actions-runner :(
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: 'true'

      - name: print env
        runs: env
        
      - name: build linux 
        run: |
          cd /_w/poky_zynqmp_generic_test/layers/poky
          . /_w/poky_zynqmp_generic_test/oe-init-build-env ../build/custom_zcu104
          bitbake core-image-minimal

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: yocto_xlnx-${{ github.sha }}
          path: /_w/poky_zynqmp_generic_test/build/tmp/deploy/images/*
          
          