name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, linux]
    container:
      image: 'ghcr.io/cracked-machine/yocto_imx:ubuntu2204'
    steps:
        # only v1 works within a self-hosted containerized actions-runner :(
      - uses: actions/checkout@v1

      - name: test
        run: echo hello
      
      # - name: build linux 
      #   run: |
      #     cd poky_zynqmp_generic_test/layers/poky
      #     source oe-init-build-env ../build/custom_zcu104
      #     bitbake core-image-minimal
      # - name: Store artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: yocto_xlnx-${{ github.sha }}
      #     path: ./build/tmp/deploy/images/qemu${{ matrix.arch }}/
      # - name: Archive production artifacts
      # uses: actions/upload-artifact@v3
      # with:
      #   name: yocto-dist-image-output
      #   path: /_w/poky_zynqmp_generic_test/build/custom_zcu104/tmp/deploy/images/custom_zcu104
          