name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, linux]
    container:
      image: 'ghcr.io/cracked-machine/yocto_xlnx:ubuntu2204'
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      # - name: build linux 
      #   run: |
      #     cd /_w/poky_zynqmp_generic_test/layers/poky
      #     source oe-init-build-env /_w/build/custom_zcu104
      #     bitbake core-image-minimal
      # - name: Archive production artifacts
      # uses: actions/upload-artifact@v3
      # with:
      #   name: yocto-dist-image-output
      #   path: /_w/poky_zynqmp_generic_test/build/custom_zcu104/tmp/deploy/images/custom_zcu104
          