name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env: 
      TEMPLATECONF: /__w/poky_zynqmp_generic_test/poky_zynqmp_generic_test/layers/meta-test/conf/templates/custom_dts
    runs-on: [self-hosted, linux]
    container:
      image: 'ghcr.io/cracked-machine/yocto_xlnx:ubuntu2204'
    steps:
        # only v1 works within a self-hosted containerized actions-runner :(
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: 'true'

      - name: print env
        run: env && ls -la ${GITHUB_WORKSPACE}
    
      - name: build linux 
        run: |
          set -x
          cd ${GITHUB_WORKSPACE}/layers/poky
          . ./oe-init-build-env ../../build/custom_zcu104
          echo $(pwd)
      #     echo ${GITHUB_WORKSPACE}
      #     bitbake core-image-minimal

      # - name: Store artifacts
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: yocto_xlnx-${{ github.sha }}
      #     path: ./build/custom_zcu104/tmp/deploy/images/*
          
          